Repository Tteonaso/Tteonaso-Backend, pull requests merged in 2024-11, with the labels that each got.

#2 Feat/#1 api response setting
  build.gradle
  build/classes/java/main/com/ssafy/Tteonaso/TteonasoApplication.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/ApiResponse.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/BaseCode.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/BaseErrorCode.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ErrorReasonDTO$ErrorReasonDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ErrorReasonDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ReasonDTO$ReasonDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ReasonDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/SuccessStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/ExceptionAdvice.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/GeneralException.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/handler/MemberHandler.class
  build/classes/java/main/com/ssafy/Tteonaso/config/SwaggerConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/converter/MemberConverter.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Gender.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtToken.class
  build/classes/java/main/com/ssafy/Tteonaso/repository/MemberRepository.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$TempTestDTO$TempTestDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$TempTestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.class
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/apiPayload/ApiResponse.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/BaseCode.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/BaseErrorCode.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/ReasonDTO.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/exception/GeneralException.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/ssafy/Tteonaso/config/SwaggerConfig.java
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Member.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/Gender.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtToken.java
  src/main/java/com/ssafy/Tteonaso/repository/MemberRepository.java
  src/main/java/com/ssafy/Tteonaso/service/MemberService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
Labels: Feat, Chore

#4 Feat/#3 spring security
  build.gradle
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/handler/JwtHandler.class
  build/classes/java/main/com/ssafy/Tteonaso/config/SecurityConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtAuthenticationFilter.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtSecurityUtil.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtToken$JwtTokenBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtToken.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtTokenProvider.class
  build/resources/main/application.properties
  build/resources/main/application.yaml
  build/tmp/compileJava/compileTransaction/stash-dir/ErrorStatus.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ExceptionAdvice.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/JwtToken.class.uniqueId2
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/exception/handler/JwtHandler.java
  src/main/java/com/ssafy/Tteonaso/config/SecurityConfig.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtSecurityUtil.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtToken.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtTokenProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: Feat, Chore

#6 🚚 chore: 환경 변수 세팅과 DB 세팅
  build.gradle
  build/resources/main/application.yaml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/resources/application.yaml
Labels: Fix, Chore

#8 Feat/#7 sign up
  build.gradle
  build/classes/java/main/com/ssafy/Tteonaso/config/MyBatisConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member$MemberBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Gender.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Status.class
  build/classes/java/main/com/ssafy/Tteonaso/repository/MemberRepository.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO$SignUpDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignUpResponseDTO$SignUpResponseDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignUpResponseDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.class
  build/resources/main/db/mapper/member.xml
  build/tmp/compileJava/compileTransaction/stash-dir/ErrorStatus.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ExceptionAdvice.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/JwtToken.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/MemberServiceImpl.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/MyBatisConfig.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/ssafy/Tteonaso/domain/Member.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/Gender.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/Status.java
  src/main/java/com/ssafy/Tteonaso/repository/MemberRepository.java
  src/main/java/com/ssafy/Tteonaso/service/MemberService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
  src/main/resources/application.yaml
Labels: Feat, Refactor, Chore

#12 Feat/#11-Sign-Up-Second
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Follow.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
Labels: Feat

#13 Revert " Feat/#11-Sign-Up-Second"
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Follow.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
Labels: Feat

#15 Feat/#14 sign in
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/config/SecurityConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/converter/MemberConverter.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Address$AddressBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Address.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Dong$DongBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Dong.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Gugun$GugunBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Gugun.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member$MemberBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Sido$SidoBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Sido.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Role.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtSecurityUtil.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtTokenProvider.class
  build/classes/java/main/com/ssafy/Tteonaso/repository/MemberRepository.class
  build/classes/java/main/com/ssafy/Tteonaso/service/CustomUserDetailService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO$SignInDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignInResponseDTO$SignInResponseDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignInResponseDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.class
  build/resources/main/application.yaml
  build/tmp/compileJava/compileTransaction/stash-dir/MemberServiceImpl.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/ssafy/Tteonaso/config/SecurityConfig.java
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Member.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/Role.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtSecurityUtil.java
  src/main/java/com/ssafy/Tteonaso/jwt/JwtTokenProvider.java
  src/main/java/com/ssafy/Tteonaso/repository/MemberRepository.java
  src/main/java/com/ssafy/Tteonaso/service/CustomUserDetailService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
  src/main/resources/application.yaml
Labels: Feat

#20 Chore: #19 Git Ignore 추가
  .gitignore
Labels: Chore

#21 Chore/address: #19 gitignore 파일 추가 전 추적 파일 삭제
  .gitignore
  build/classes/java/main/com/ssafy/Tteonaso/TteonasoApplication.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/ApiResponse.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/BaseCode.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/BaseErrorCode.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ErrorReasonDTO$ErrorReasonDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ErrorReasonDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ReasonDTO$ReasonDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/ReasonDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/ErrorStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/code/status/SuccessStatus.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/ExceptionAdvice.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/GeneralException.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/handler/JwtHandler.class
  build/classes/java/main/com/ssafy/Tteonaso/apiPayload/exception/handler/MemberHandler.class
  build/classes/java/main/com/ssafy/Tteonaso/config/SecurityConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/config/SwaggerConfig.class
  build/classes/java/main/com/ssafy/Tteonaso/converter/MemberConverter.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Address$AddressBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Address.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Follow$FollowBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Follow.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member$MemberBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/Member.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/common/BaseEntity.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Gender.class
  build/classes/java/main/com/ssafy/Tteonaso/domain/enums/Status.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtAuthenticationFilter.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtSecurityUtil.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtToken$JwtTokenBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtToken.class
  build/classes/java/main/com/ssafy/Tteonaso/jwt/JwtTokenProvider.class
  build/classes/java/main/com/ssafy/Tteonaso/repository/MemberRepository.class
  build/classes/java/main/com/ssafy/Tteonaso/service/CustomUserDetailService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberService.class
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO$SignInDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO$SignUpDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignInResponseDTO$SignInResponseDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignInResponseDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignUpResponseDTO$SignUpResponseDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$SignUpResponseDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$TempTestDTO$TempTestDTOBuilder.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO$TempTestDTO.class
  build/classes/java/main/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.class
  build/resources/main/application.yaml
  build/tmp/compileJava/compileTransaction/stash-dir/MemberServiceImpl.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  gradlew
  gradlew.bat
  src/main/java/com/ssafy/Tteonaso/domain/Address.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
Labels: Chore

#22 Feature/Address/ #18 주소 조회 기능 구현
  src/main/java/com/ssafy/Tteonaso/domain/Address.java
  src/main/java/com/ssafy/Tteonaso/domain/PlaceCategory.java
  src/main/java/com/ssafy/Tteonaso/repository/MapFilterRepository.java
  src/main/java/com/ssafy/Tteonaso/service/MapFilterService.java
  src/main/java/com/ssafy/Tteonaso/service/MapFilterServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MapFilterRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MapFilterRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MapFilterResponseDTO.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: Feat

#26 Feat/#25 read all chat room
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/converter/ChatRoomConverter.java
  src/main/java/com/ssafy/Tteonaso/repository/ChatRoomRepository.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomService.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/ChatRoomRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/ChatRoomResponseDTO.java
  src/main/resources/application.yaml
Labels: Feat

#28 Fix/#27-Read-All-ChatRoom-Fix
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/converter/ChatRoomConverter.java
  src/main/java/com/ssafy/Tteonaso/web/dto/ChatRoomResponseDTO.java
Labels: Fix

#34 Feat/#33 get member info
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/service/MemberService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
Labels: Feat

#35 Feature/Gpt-Travel-Schedule/#32 GPT 여행 일정 설계 기능 구현
  build.gradle
  src/main/java/com/ssafy/Tteonaso/config/WebClientConfig.java
  src/main/java/com/ssafy/Tteonaso/converter/GptEnumConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/CompanionType.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/SchedulePreference.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/TravelDestination.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/TravelDuration.java
  src/main/java/com/ssafy/Tteonaso/domain/enums/TravelStyle.java
  src/main/java/com/ssafy/Tteonaso/service/GptService.java
  src/main/java/com/ssafy/Tteonaso/service/GptServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/GptTravelRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptEnumResponseDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptTravelRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptTravelResponseDTO.java
Labels: Feat

#38 Feature/Logs/#37 로깅 처리
  build.gradle
  src/main/java/com/ssafy/Tteonaso/TteonasoApplication.java
  src/main/java/com/ssafy/Tteonaso/config/AwsS3Config.java
  src/main/java/com/ssafy/Tteonaso/config/LogDirectoryInitializer.java
  src/main/java/com/ssafy/Tteonaso/config/LogbackConfig.java
  src/main/java/com/ssafy/Tteonaso/config/WebConfig.java
  src/main/java/com/ssafy/Tteonaso/logging/MattermostAppender.java
  src/main/java/com/ssafy/Tteonaso/scheduler/LogUploadScheduler.java
  src/main/java/com/ssafy/Tteonaso/service/LoggingService.java
  src/main/java/com/ssafy/Tteonaso/service/MattermostLoggingService.java
  src/main/java/com/ssafy/Tteonaso/service/S3UploaderService.java
  src/main/resources/data.sql
Labels: Feat, Refactor

#42 Feat/#36 chat room search
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/repository/ChatRoomRepository.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomService.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/ChatRoomRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/ChatRoomRequestDTO.java
Labels: Feat

#44 Fix/#43-Search-ChatRoom
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomService.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/ChatRoomRestController.java
Labels: Fix

#47 Fix/Response-Dto/#46. 응답 클래스 파일명 변경
  build.gradle
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  src/main/java/com/ssafy/Tteonaso/apiPayload/ApiResponseDTO.java
  src/main/java/com/ssafy/Tteonaso/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/ssafy/Tteonaso/scheduler/LogUploadScheduler.java
  src/main/java/com/ssafy/Tteonaso/web/controller/ChatRoomRestController.java
  src/main/java/com/ssafy/Tteonaso/web/controller/GptTravelRestController.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MapFilterRestController.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/ChatRoomResponseDTO.java
  src/main/resources/application.yaml
Labels: Fix

#48 Feat/#45 update member info
  build/classes/java/main/com/ssafy/Tteonaso/service/MemberServiceImpl.class
  build/classes/java/main/com/ssafy/Tteonaso/web/controller/MemberRestController.class
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Member.java
  src/main/java/com/ssafy/Tteonaso/service/MemberService.java
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MemberRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
Labels: Feat

#50 Docs/Swagger/#49. 유저 제외 Swagger 문서화 등록
  src/main/java/com/ssafy/Tteonaso/apiPayload/ApiResponseDTO.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomService.java
  src/main/java/com/ssafy/Tteonaso/service/ChatRoomServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/controller/ChatRoomRestController.java
  src/main/java/com/ssafy/Tteonaso/web/controller/GptTravelRestController.java
  src/main/java/com/ssafy/Tteonaso/web/controller/MapFilterRestController.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptEnumResponseDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptTravelRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/GptTravelResponseDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MapFilterRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MapFilterResponseDTO.java
Labels: Docs

#52 Fix/#51-Update-Profile-DTO
  build.gradle
  src/main/java/com/ssafy/Tteonaso/converter/MemberConverter.java
  src/main/java/com/ssafy/Tteonaso/domain/Member.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberResponseDTO.java
  src/main/resources/application.yaml
Labels: Fix

#54 Fix/#53 update member info
  src/main/java/com/ssafy/Tteonaso/service/MemberServiceImpl.java
  src/main/java/com/ssafy/Tteonaso/web/dto/MemberRequestDTO.java
Labels: Fix
